//! ISO 3166-1 alpha-2 codes and English names.
//!
//! The code list is the current ISO 3166-1 table published at
//! <https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes>.
//! Display names drop the parenthetical ISO wording. Common news-wire
//! names are kept as aliases so a headline can still be placed.

/// Alpha-2 code and the name shown in the product.
pub const CODES: &[(&str, &str)] = &[
    ("ad", "Andorra"),
    ("ae", "United Arab Emirates"),
    ("af", "Afghanistan"),
    ("ag", "Antigua and Barbuda"),
    ("ai", "Anguilla"),
    ("al", "Albania"),
    ("am", "Armenia"),
    ("ao", "Angola"),
    ("aq", "Antarctica"),
    ("ar", "Argentina"),
    ("as", "American Samoa"),
    ("at", "Austria"),
    ("au", "Australia"),
    ("aw", "Aruba"),
    ("ax", "Åland Islands"),
    ("az", "Azerbaijan"),
    ("ba", "Bosnia and Herzegovina"),
    ("bb", "Barbados"),
    ("bd", "Bangladesh"),
    ("be", "Belgium"),
    ("bf", "Burkina Faso"),
    ("bg", "Bulgaria"),
    ("bh", "Bahrain"),
    ("bi", "Burundi"),
    ("bj", "Benin"),
    ("bl", "Saint Barthélemy"),
    ("bm", "Bermuda"),
    ("bn", "Brunei Darussalam"),
    ("bo", "Bolivia"),
    ("bq", "Bonaire, Sint Eustatius and Saba"),
    ("br", "Brazil"),
    ("bs", "Bahamas"),
    ("bt", "Bhutan"),
    ("bv", "Bouvet Island"),
    ("bw", "Botswana"),
    ("by", "Belarus"),
    ("bz", "Belize"),
    ("ca", "Canada"),
    ("cc", "Cocos (Keeling) Islands"),
    ("cd", "Democratic Republic of the Congo"),
    ("cf", "Central African Republic"),
    ("cg", "Congo"),
    ("ch", "Switzerland"),
    ("ci", "Côte d'Ivoire"),
    ("ck", "Cook Islands"),
    ("cl", "Chile"),
    ("cm", "Cameroon"),
    ("cn", "China"),
    ("co", "Colombia"),
    ("cr", "Costa Rica"),
    ("cu", "Cuba"),
    ("cv", "Cabo Verde"),
    ("cw", "Curaçao"),
    ("cx", "Christmas Island"),
    ("cy", "Cyprus"),
    ("cz", "Czechia"),
    ("de", "Germany"),
    ("dj", "Djibouti"),
    ("dk", "Denmark"),
    ("dm", "Dominica"),
    ("do", "Dominican Republic"),
    ("dz", "Algeria"),
    ("ec", "Ecuador"),
    ("ee", "Estonia"),
    ("eg", "Egypt"),
    ("eh", "Western Sahara"),
    ("er", "Eritrea"),
    ("es", "Spain"),
    ("et", "Ethiopia"),
    ("fi", "Finland"),
    ("fj", "Fiji"),
    ("fk", "Falkland Islands"),
    ("fm", "Micronesia"),
    ("fo", "Faroe Islands"),
    ("fr", "France"),
    ("ga", "Gabon"),
    ("gb", "United Kingdom"),
    ("gd", "Grenada"),
    ("ge", "Georgia"),
    ("gf", "French Guiana"),
    ("gg", "Guernsey"),
    ("gh", "Ghana"),
    ("gi", "Gibraltar"),
    ("gl", "Greenland"),
    ("gm", "Gambia"),
    ("gn", "Guinea"),
    ("gp", "Guadeloupe"),
    ("gq", "Equatorial Guinea"),
    ("gr", "Greece"),
    ("gs", "South Georgia and the South Sandwich Islands"),
    ("gt", "Guatemala"),
    ("gu", "Guam"),
    ("gw", "Guinea-Bissau"),
    ("gy", "Guyana"),
    ("hk", "Hong Kong"),
    ("hm", "Heard Island and McDonald Islands"),
    ("hn", "Honduras"),
    ("hr", "Croatia"),
    ("ht", "Haiti"),
    ("hu", "Hungary"),
    ("id", "Indonesia"),
    ("ie", "Ireland"),
    ("il", "Israel"),
    ("im", "Isle of Man"),
    ("in", "India"),
    ("io", "British Indian Ocean Territory"),
    ("iq", "Iraq"),
    ("ir", "Iran"),
    ("is", "Iceland"),
    ("it", "Italy"),
    ("je", "Jersey"),
    ("jm", "Jamaica"),
    ("jo", "Jordan"),
    ("jp", "Japan"),
    ("ke", "Kenya"),
    ("kg", "Kyrgyzstan"),
    ("kh", "Cambodia"),
    ("ki", "Kiribati"),
    ("km", "Comoros"),
    ("kn", "Saint Kitts and Nevis"),
    ("kp", "North Korea"),
    ("kr", "South Korea"),
    ("kw", "Kuwait"),
    ("ky", "Cayman Islands"),
    ("kz", "Kazakhstan"),
    ("la", "Laos"),
    ("lb", "Lebanon"),
    ("lc", "Saint Lucia"),
    ("li", "Liechtenstein"),
    ("lk", "Sri Lanka"),
    ("lr", "Liberia"),
    ("ls", "Lesotho"),
    ("lt", "Lithuania"),
    ("lu", "Luxembourg"),
    ("lv", "Latvia"),
    ("ly", "Libya"),
    ("ma", "Morocco"),
    ("mc", "Monaco"),
    ("md", "Moldova"),
    ("me", "Montenegro"),
    ("mf", "Saint Martin (French part)"),
    ("mg", "Madagascar"),
    ("mh", "Marshall Islands"),
    ("mk", "North Macedonia"),
    ("ml", "Mali"),
    ("mm", "Myanmar"),
    ("mn", "Mongolia"),
    ("mo", "Macao"),
    ("mp", "Northern Mariana Islands"),
    ("mq", "Martinique"),
    ("mr", "Mauritania"),
    ("ms", "Montserrat"),
    ("mt", "Malta"),
    ("mu", "Mauritius"),
    ("mv", "Maldives"),
    ("mw", "Malawi"),
    ("mx", "Mexico"),
    ("my", "Malaysia"),
    ("mz", "Mozambique"),
    ("na", "Namibia"),
    ("nc", "New Caledonia"),
    ("ne", "Niger"),
    ("nf", "Norfolk Island"),
    ("ng", "Nigeria"),
    ("ni", "Nicaragua"),
    ("nl", "Netherlands"),
    ("no", "Norway"),
    ("np", "Nepal"),
    ("nr", "Nauru"),
    ("nu", "Niue"),
    ("nz", "New Zealand"),
    ("om", "Oman"),
    ("pa", "Panama"),
    ("pe", "Peru"),
    ("pf", "French Polynesia"),
    ("pg", "Papua New Guinea"),
    ("ph", "Philippines"),
    ("pk", "Pakistan"),
    ("pl", "Poland"),
    ("pm", "Saint Pierre and Miquelon"),
    ("pn", "Pitcairn"),
    ("pr", "Puerto Rico"),
    ("ps", "Palestine, State of"),
    ("pt", "Portugal"),
    ("pw", "Palau"),
    ("py", "Paraguay"),
    ("qa", "Qatar"),
    ("re", "Réunion"),
    ("ro", "Romania"),
    ("rs", "Serbia"),
    ("ru", "Russia"),
    ("rw", "Rwanda"),
    ("sa", "Saudi Arabia"),
    ("sb", "Solomon Islands"),
    ("sc", "Seychelles"),
    ("sd", "Sudan"),
    ("se", "Sweden"),
    ("sg", "Singapore"),
    ("sh", "Saint Helena, Ascension and Tristan da Cunha"),
    ("si", "Slovenia"),
    ("sj", "Svalbard and Jan Mayen"),
    ("sk", "Slovakia"),
    ("sl", "Sierra Leone"),
    ("sm", "San Marino"),
    ("sn", "Senegal"),
    ("so", "Somalia"),
    ("sr", "Suriname"),
    ("ss", "South Sudan"),
    ("st", "Sao Tome and Principe"),
    ("sv", "El Salvador"),
    ("sx", "Sint Maarten (Dutch part)"),
    ("sy", "Syria"),
    ("sz", "Eswatini"),
    ("tc", "Turks and Caicos Islands"),
    ("td", "Chad"),
    ("tf", "French Southern Territories"),
    ("tg", "Togo"),
    ("th", "Thailand"),
    ("tj", "Tajikistan"),
    ("tk", "Tokelau"),
    ("tl", "Timor-Leste"),
    ("tm", "Turkmenistan"),
    ("tn", "Tunisia"),
    ("to", "Tonga"),
    ("tr", "Turkey"),
    ("tt", "Trinidad and Tobago"),
    ("tv", "Tuvalu"),
    ("tw", "Taiwan"),
    ("tz", "Tanzania"),
    ("ua", "Ukraine"),
    ("ug", "Uganda"),
    ("um", "United States Minor Outlying Islands"),
    ("us", "United States"),
    ("uy", "Uruguay"),
    ("uz", "Uzbekistan"),
    ("va", "Holy See"),
    ("vc", "Saint Vincent and the Grenadines"),
    ("ve", "Venezuela"),
    ("vg", "Virgin Islands (British)"),
    ("vi", "Virgin Islands (U.S.)"),
    ("vn", "Vietnam"),
    ("vu", "Vanuatu"),
    ("wf", "Wallis and Futuna"),
    ("ws", "Samoa"),
    ("ye", "Yemen"),
    ("yt", "Mayotte"),
    ("za", "South Africa"),
    ("zm", "Zambia"),
    ("zw", "Zimbabwe"),
];

/// Lowercase place name, including ISO wording and everyday aliases.
const NAMES: &[(&str, &str)] = &[
    ("afghanistan", "af"),
    ("albania", "al"),
    ("algeria", "dz"),
    ("american samoa", "as"),
    ("andorra", "ad"),
    ("angola", "ao"),
    ("anguilla", "ai"),
    ("antarctica", "aq"),
    ("antigua and barbuda", "ag"),
    ("argentina", "ar"),
    ("armenia", "am"),
    ("aruba", "aw"),
    ("australia", "au"),
    ("austria", "at"),
    ("azerbaijan", "az"),
    ("bahamas", "bs"),
    ("bahamas (the)", "bs"),
    ("bahrain", "bh"),
    ("bangladesh", "bd"),
    ("barbados", "bb"),
    ("belarus", "by"),
    ("belgium", "be"),
    ("belize", "bz"),
    ("benin", "bj"),
    ("bermuda", "bm"),
    ("bhutan", "bt"),
    ("bolivia", "bo"),
    ("bolivia (plurinational state of)", "bo"),
    ("bonaire sint eustatius saba", "bq"),
    ("bonaire, sint eustatius and saba", "bq"),
    ("bosnia and herzegovina", "ba"),
    ("botswana", "bw"),
    ("bouvet island", "bv"),
    ("brazil", "br"),
    ("britain", "gb"),
    ("british indian ocean territory", "io"),
    ("british indian ocean territory (the)", "io"),
    ("brunei darussalam", "bn"),
    ("bulgaria", "bg"),
    ("burkina faso", "bf"),
    ("burma", "mm"),
    ("burundi", "bi"),
    ("cabo verde", "cv"),
    ("cambodia", "kh"),
    ("cameroon", "cm"),
    ("canada", "ca"),
    ("cape verde", "cv"),
    ("cayman islands", "ky"),
    ("cayman islands (the)", "ky"),
    ("central african republic", "cf"),
    ("central african republic (the)", "cf"),
    ("chad", "td"),
    ("chile", "cl"),
    ("china", "cn"),
    ("christmas island", "cx"),
    ("cocos (keeling) islands", "cc"),
    ("cocos (keeling) islands (the)", "cc"),
    ("colombia", "co"),
    ("comoros", "km"),
    ("comoros (the)", "km"),
    ("congo", "cg"),
    ("congo (the democratic republic of the)", "cd"),
    ("congo (the)", "cg"),
    ("cook islands", "ck"),
    ("cook islands (the)", "ck"),
    ("costa rica", "cr"),
    ("croatia", "hr"),
    ("cuba", "cu"),
    ("curaçao", "cw"),
    ("cyprus", "cy"),
    ("czech republic", "cz"),
    ("czechia", "cz"),
    ("côte d'ivoire", "ci"),
    ("democratic republic of the congo", "cd"),
    ("denmark", "dk"),
    ("djibouti", "dj"),
    ("dominica", "dm"),
    ("dominican republic", "do"),
    ("dominican republic (the)", "do"),
    ("dr congo", "cd"),
    ("drc", "cd"),
    ("east timor", "tl"),
    ("ecuador", "ec"),
    ("egypt", "eg"),
    ("el salvador", "sv"),
    ("equatorial guinea", "gq"),
    ("eritrea", "er"),
    ("estonia", "ee"),
    ("eswatini", "sz"),
    ("ethiopia", "et"),
    ("falkland islands", "fk"),
    ("falkland islands (the)", "fk"),
    ("faroe islands", "fo"),
    ("faroe islands (the)", "fo"),
    ("fiji", "fj"),
    ("finland", "fi"),
    ("france", "fr"),
    ("french guiana", "gf"),
    ("french polynesia", "pf"),
    ("french southern territories", "tf"),
    ("french southern territories (the)", "tf"),
    ("gabon", "ga"),
    ("gambia", "gm"),
    ("gambia (the)", "gm"),
    ("georgia", "ge"),
    ("germany", "de"),
    ("ghana", "gh"),
    ("gibraltar", "gi"),
    ("great britain", "gb"),
    ("greece", "gr"),
    ("greenland", "gl"),
    ("grenada", "gd"),
    ("guadeloupe", "gp"),
    ("guam", "gu"),
    ("guatemala", "gt"),
    ("guernsey", "gg"),
    ("guinea", "gn"),
    ("guinea-bissau", "gw"),
    ("guyana", "gy"),
    ("haiti", "ht"),
    ("heard island and mcdonald islands", "hm"),
    ("holland", "nl"),
    ("holy see", "va"),
    ("holy see (the)", "va"),
    ("honduras", "hn"),
    ("hong kong", "hk"),
    ("hungary", "hu"),
    ("iceland", "is"),
    ("india", "in"),
    ("indonesia", "id"),
    ("iran", "ir"),
    ("iran (islamic republic of)", "ir"),
    ("iraq", "iq"),
    ("ireland", "ie"),
    ("isle of man", "im"),
    ("israel", "il"),
    ("italy", "it"),
    ("ivory coast", "ci"),
    ("jamaica", "jm"),
    ("japan", "jp"),
    ("jersey", "je"),
    ("jordan", "jo"),
    ("kazakhstan", "kz"),
    ("kenya", "ke"),
    ("kiribati", "ki"),
    ("korea", "kr"),
    ("korea (the democratic people's republic of)", "kp"),
    ("korea (the republic of)", "kr"),
    ("kuwait", "kw"),
    ("kyrgyzstan", "kg"),
    ("lao people's democratic republic", "la"),
    ("lao people's democratic republic (the)", "la"),
    ("laos", "la"),
    ("latvia", "lv"),
    ("lebanon", "lb"),
    ("lesotho", "ls"),
    ("liberia", "lr"),
    ("libya", "ly"),
    ("liechtenstein", "li"),
    ("lithuania", "lt"),
    ("luxembourg", "lu"),
    ("macao", "mo"),
    ("macau", "mo"),
    ("madagascar", "mg"),
    ("malawi", "mw"),
    ("malaysia", "my"),
    ("maldives", "mv"),
    ("mali", "ml"),
    ("malta", "mt"),
    ("marshall islands", "mh"),
    ("marshall islands (the)", "mh"),
    ("martinique", "mq"),
    ("mauritania", "mr"),
    ("mauritius", "mu"),
    ("mayotte", "yt"),
    ("mexico", "mx"),
    ("micronesia", "fm"),
    ("micronesia (federated states of)", "fm"),
    ("moldova", "md"),
    ("moldova (the republic of)", "md"),
    ("monaco", "mc"),
    ("mongolia", "mn"),
    ("montenegro", "me"),
    ("montserrat", "ms"),
    ("morocco", "ma"),
    ("mozambique", "mz"),
    ("myanmar", "mm"),
    ("namibia", "na"),
    ("naoero", "nr"),
    ("nauru", "nr"),
    ("nepal", "np"),
    ("netherlands", "nl"),
    ("netherlands (kingdom of the)", "nl"),
    ("new caledonia", "nc"),
    ("new zealand", "nz"),
    ("nicaragua", "ni"),
    ("niger", "ne"),
    ("niger (the)", "ne"),
    ("nigeria", "ng"),
    ("niue", "nu"),
    ("norfolk island", "nf"),
    ("north korea", "kp"),
    ("north macedonia", "mk"),
    ("northern mariana islands", "mp"),
    ("northern mariana islands (the)", "mp"),
    ("norway", "no"),
    ("oman", "om"),
    ("pakistan", "pk"),
    ("palau", "pw"),
    ("palestine", "ps"),
    ("palestine, state of", "ps"),
    ("panama", "pa"),
    ("papua new guinea", "pg"),
    ("paraguay", "py"),
    ("peru", "pe"),
    ("philippines", "ph"),
    ("philippines (the)", "ph"),
    ("pitcairn", "pn"),
    ("poland", "pl"),
    ("portugal", "pt"),
    ("puerto rico", "pr"),
    ("qatar", "qa"),
    ("republic of korea", "kr"),
    ("romania", "ro"),
    ("russia", "ru"),
    ("russian federation", "ru"),
    ("russian federation (the)", "ru"),
    ("rwanda", "rw"),
    ("réunion", "re"),
    ("saint barthélemy", "bl"),
    ("saint helena ascension island tristan da cunha", "sh"),
    ("saint helena, ascension and tristan da cunha", "sh"),
    ("saint kitts and nevis", "kn"),
    ("saint lucia", "lc"),
    ("saint martin (french part)", "mf"),
    ("saint pierre and miquelon", "pm"),
    ("saint vincent and the grenadines", "vc"),
    ("samoa", "ws"),
    ("san marino", "sm"),
    ("sao tome and principe", "st"),
    ("saudi arabia", "sa"),
    ("senegal", "sn"),
    ("serbia", "rs"),
    ("seychelles", "sc"),
    ("sierra leone", "sl"),
    ("singapore", "sg"),
    ("sint maarten (dutch part)", "sx"),
    ("slovakia", "sk"),
    ("slovenia", "si"),
    ("solomon islands", "sb"),
    ("somalia", "so"),
    ("south africa", "za"),
    ("south georgia and the south sandwich islands", "gs"),
    ("south korea", "kr"),
    ("south sudan", "ss"),
    ("spain", "es"),
    ("sri lanka", "lk"),
    ("sudan", "sd"),
    ("sudan (the)", "sd"),
    ("suriname", "sr"),
    ("svalbard and jan mayen", "sj"),
    ("svalbard jan mayen", "sj"),
    ("swaziland", "sz"),
    ("sweden", "se"),
    ("switzerland", "ch"),
    ("syria", "sy"),
    ("syrian arab republic", "sy"),
    ("syrian arab republic (the)", "sy"),
    ("taiwan", "tw"),
    ("taiwan (province of china)", "tw"),
    ("tajikistan", "tj"),
    ("tanzania", "tz"),
    ("tanzania, the united republic of", "tz"),
    ("thailand", "th"),
    ("timor-leste", "tl"),
    ("togo", "tg"),
    ("tokelau", "tk"),
    ("tonga", "to"),
    ("trinidad and tobago", "tt"),
    ("tunisia", "tn"),
    ("turkey", "tr"),
    ("turkmenistan", "tm"),
    ("turks and caicos islands", "tc"),
    ("turks and caicos islands (the)", "tc"),
    ("tuvalu", "tv"),
    ("türkiye", "tr"),
    ("uae", "ae"),
    ("uganda", "ug"),
    ("uk", "gb"),
    ("ukraine", "ua"),
    ("united arab emirates", "ae"),
    ("united arab emirates (the)", "ae"),
    ("united kingdom", "gb"),
    ("united kingdom of great britain and northern ireland", "gb"),
    (
        "united kingdom of great britain and northern ireland (the)",
        "gb",
    ),
    ("united states", "us"),
    ("united states minor outlying islands", "um"),
    ("united states minor outlying islands (the)", "um"),
    ("united states of america", "us"),
    ("united states of america (the)", "us"),
    ("uruguay", "uy"),
    ("usa", "us"),
    ("uzbekistan", "uz"),
    ("vanuatu", "vu"),
    ("vatican", "va"),
    ("vatican city", "va"),
    ("venezuela", "ve"),
    ("venezuela (bolivarian republic of)", "ve"),
    ("viet nam", "vn"),
    ("vietnam", "vn"),
    ("virgin islands (british)", "vg"),
    ("virgin islands (u.s.)", "vi"),
    ("wallis and futuna", "wf"),
    ("western sahara", "eh"),
    ("yemen", "ye"),
    ("zambia", "zm"),
    ("zimbabwe", "zw"),
    ("åland islands", "ax"),
];

/// English name for an alpha-2 code.
pub fn name(code: &str) -> Option<&'static str> {
    let code = code.trim().to_ascii_lowercase();
    CODES
        .binary_search_by(|row| row.0.cmp(code.as_str()))
        .ok()
        .map(|index| CODES[index].1)
}

/// Alpha-2 code for an English or ISO country name.
pub fn code_for_name(name: &str) -> Option<&'static str> {
    let name = name
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .to_ascii_lowercase();
    if name.is_empty() {
        return None;
    }
    NAMES
        .binary_search_by(|row| row.0.cmp(name.as_str()))
        .ok()
        .map(|index| NAMES[index].1)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_iso_table_names_qatar_and_covers_every_code() {
        assert_eq!(CODES.len(), 249);
        assert_eq!(name("qa"), Some("Qatar"));
        assert_eq!(code_for_name("Qatar"), Some("qa"));
        assert_eq!(name("zz"), None);
    }
}
