//! Holehe upstream service inventory pinned at 14da70f (123 modules).
//! Generated from the audited tree; adapters are native, not copied from GPL sources.

use super::{ServiceSpec, ServiceState};

pub const UPSTREAM_COMMIT: &str = "14da70f588538936b20d238783c5e28a0772a2b3";
pub const CATALOG_LEN: usize = 123;

pub const CATALOG: &[ServiceSpec] = &[
    ServiceSpec {
        id: "atlassian",
        category: "cms",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "gravatar",
        category: "cms",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "voxmedia",
        category: "cms",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "wordpress",
        category: "cms",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "conflates unverified/email-login restrictions with absence",
    },
    ServiceSpec {
        id: "aboutme",
        category: "company",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "amocrm",
        category: "crm",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "axonaut",
        category: "crm",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "hubspot",
        category: "crm",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "insightly",
        category: "crm",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "nimble",
        category: "crm",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "nocrm",
        category: "crm",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "nutshell",
        category: "crm",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "pipedrive",
        category: "crm",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "teamleader",
        category: "crm",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "zoho",
        category: "crm",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "buymeacoffee",
        category: "crowfunding",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "babeshows",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "badeggsonline",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "biosmods",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "biotechnologyforums",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "blackworldforum",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "blitzortung",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "bluegrassrivals",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "cambridgemt",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "chinaphonearena",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "clashfarmer",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "codeigniter",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "cpaelites",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "cpahero",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "cracked_to",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "demonforums",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "freiberg",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "koditv",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "mybb",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "nattyornot",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "ndemiccreations",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "nextpvr",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "onlinesequencer",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "thecardboard",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "therianguide",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "thevapingforum",
        category: "forum",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "coroflot",
        category: "jobs",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "freelancer",
        category: "jobs",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "seoclerks",
        category: "jobs",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "diigo",
        category: "learning",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "duolingo",
        category: "learning",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "quora",
        category: "learning",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "google",
        category: "mails",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "laposte",
        category: "mails",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "mail_ru",
        category: "mails",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "protonmail",
        category: "mails",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "yahoo",
        category: "mails",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "ello",
        category: "medias",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "flickr",
        category: "medias",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "komoot",
        category: "medias",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "rambler",
        category: "medias",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "sporcle",
        category: "medias",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "caringbridge",
        category: "medical",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "sevencups",
        category: "medical",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "blip",
        category: "music",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "lastfm",
        category: "music",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "smule",
        category: "music",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "soundcloud",
        category: "music",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "spotify",
        category: "music",
        method: "GET",
        hosts: &["spclient.wg.spotify.com"],
        adapter_version: "1.0",
        state: ServiceState::Experimental,
        fixture_validated: true,
        live_validated: false,
        unsupported_reason: "",
    },
    ServiceSpec {
        id: "tunefind",
        category: "music",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "rocketreach",
        category: "osint",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "venmo",
        category: "payment",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "pornhub",
        category: "porn",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "redtube",
        category: "porn",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "xnxx",
        category: "porn",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "xvideos",
        category: "porn",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "anydo",
        category: "productivity",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "evernote",
        category: "productivity",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "eventbrite",
        category: "products",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "nike",
        category: "products",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "samsung",
        category: "products",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "codecademy",
        category: "programing",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "codepen",
        category: "programing",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "devrant",
        category: "programing",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "github",
        category: "programing",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "CSRF plus signup_check/email with overbroad 422 inference",
    },
    ServiceSpec {
        id: "replit",
        category: "programing",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "teamtreehouse",
        category: "programing",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "vrbo",
        category: "real_estate",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "amazon",
        category: "shopping",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "armurerieauxerre",
        category: "shopping",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "deliveroo",
        category: "shopping",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "dominosfr",
        category: "shopping",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "ebay",
        category: "shopping",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "envato",
        category: "shopping",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "garmin",
        category: "shopping",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "naturabuy",
        category: "shopping",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "vivino",
        category: "shopping",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "bitmoji",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "crevado",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "discord",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "facebook",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "fanpop",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "imgur",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "instagram",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason:
            "signup CSRF then web_create_ajax/attempt has ambiguous/missing-result branches",
    },
    ServiceSpec {
        id: "myspace",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "odnoklassniki",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "parler",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "patreon",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "pinterest",
        category: "social_media",
        method: "GET",
        hosts: &["www.pinterest.com"],
        adapter_version: "1.0",
        state: ServiceState::Experimental,
        fixture_validated: true,
        live_validated: false,
        unsupported_reason: "",
    },
    ServiceSpec {
        id: "plurk",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "snapchat",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "strava",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "taringa",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "tellonym",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "tumblr",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "twitter",
        category: "social_media",
        method: "GET",
        hosts: &["api.twitter.com"],
        adapter_version: "1.0",
        state: ServiceState::Experimental,
        fixture_validated: true,
        live_validated: false,
        unsupported_reason: "",
    },
    ServiceSpec {
        id: "vsco",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "wattpad",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "xing",
        category: "social_media",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "adobe",
        category: "software",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "archive",
        category: "software",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "docker",
        category: "software",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "posts signup data and treats any other response as negative",
    },
    ServiceSpec {
        id: "firefox",
        category: "software",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "issuu",
        category: "software",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "lastpass",
        category: "software",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "office365",
        category: "software",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "bodybuilding",
        category: "sport",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
    ServiceSpec {
        id: "blablacar",
        category: "transport",
        method: "GET",
        hosts: &[],
        adapter_version: "1.0",
        state: ServiceState::Unsupported,
        fixture_validated: false,
        live_validated: false,
        unsupported_reason: "not implemented in this increment",
    },
];

pub fn by_id(id: &str) -> Option<&'static ServiceSpec> {
    CATALOG.iter().find(|s| s.id == id)
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn catalog_has_123_unique_ids() {
        assert_eq!(CATALOG.len(), CATALOG_LEN);
        let mut ids: Vec<_> = CATALOG.iter().map(|s| s.id).collect();
        ids.sort_unstable();
        ids.dedup();
        assert_eq!(ids.len(), 123);
        assert!(by_id("twitter").unwrap().implemented());
        assert!(by_id("spotify").unwrap().implemented());
        assert!(by_id("pinterest").unwrap().implemented());
        assert!(by_id("twitter").unwrap().fixture_validated);
        assert!(by_id("spotify").unwrap().fixture_validated);
        assert!(by_id("pinterest").unwrap().fixture_validated);
        assert!(!by_id("twitter").unwrap().live_validated);
        assert!(!by_id("spotify").unwrap().live_validated);
        assert!(!by_id("pinterest").unwrap().live_validated);
        assert!(!by_id("instagram").unwrap().implemented());
        assert!(!by_id("github").unwrap().implemented());
        assert!(!by_id("docker").unwrap().implemented());
        assert!(!by_id("wordpress").unwrap().implemented());
    }
}
